### ISSUE TITLE
Can't find ssh.py

### ISSUE THREAD

**Issue by CrashyBang** [joaojacome/bitwarden-ssh-agent#1]
When running:
```bash
~/path/to/repo/start.sh
```
Getting the following error:
```
python: can't open file 'ssh.py': [Errno 2] No such file or directory
```
Could it be because I am using ` ~/ ` ?

**Comment by joaojacome** [comment]
Please test the related branch and see if it solves your issue. I reproduced it here and now it's working fine :)

**Comment by CrashyBang** [comment]
Sorry took so long to get back :) Working!
