### ISSUE TITLE
Passphrase support?

### ISSUE THREAD

**Issue by haneef95** [joaojacome/bitwarden-ssh-agent#12]
Hi,

This is a nice and simple piece of kit! Thanks! 👍 

Does this support SSH Keys with Passphrases? Like [KeeAgent](https://keeagent.readthedocs.io/en/stable/usage/quick-start.html)

Kind regards,

**Comment by strasharo** [comment]
Is it able to read it from the secure note entry or the only way is to enter it manually when loading through the cli?

**Comment by p-hash** [comment]
Looks like @strasharo is right and the only way to provide a passphrase for a key is to type it manually.

In my opinion, this is enough to reopen the issue.

 @joaojacome Let's come up with ideas how to store ssh key passphrase in same secure note. I think the best way would be to add another custom field named `passphrase` and read it from there.

**Comment by joaojacome** [comment]
Maybe there's a way to pass the passphrase to ssh-add using the env var SSH_ASKPASS
Ref: https://linux.die.net/man/1/ssh-add

If possible, I'd rather go with this option than having an extra dependency.

**Comment by p-hash** [comment]
@joaojacome I managed to solve this in #22
