### ISSUE TITLE
ssh-add always asks for password

### ISSUE THREAD

**Issue by zjean** [joaojacome/bitwarden-ssh-agent#26]
Hi,

Thanks for this useful tool!
The weird thing is, I always get the question from ssh-add to enter the keyphrase:
```
INFO:root:Getting Bitwarden session
DEBUG:root:Bitwarden vault is locked
? Master password: [hidden]
INFO:root:To re-use this BitWarden session run: export BW_SESSION=“XX”
DEBUG:root:Session = XX
INFO:root:Getting folder list
DEBUG:root:Folder name: ssh-agent
INFO:root:Getting folder items
DEBUG:root:Folder ID: 08a058db-cecc-4c4a-b0f9-111500bf1e7a
INFO:root:Attempting to add keys to ssh-agent
DEBUG:root:Private key file declared
DEBUG:root:Passphrase declared
DEBUG:root:Private key ID found
DEBUG:root:Item ID: 5f799525-4849-4aba-a6a1-1116012d1ad8
DEBUG:root:Key ID: co6dah0ygsimglfcj8087k7x3vu71211
DEBUG:root:Running ssh-add
Enter passphrase for (stdin):
Identity added: (stdin) (KEY)
```

It also doesn't show the correct name, but instead shows `(stdin)`

This is my configuration:

![image](https://user-images.githubusercontent.com/441924/183239575-56bbfaf9-4af4-4aa6-931a-f784cd10c072.png)

Any suggestions?

**Comment by joaojacome** [comment]
Hello! 

Could you check if it works by passing `SSH_ASKPASS_REQUIRE=force` when calling the tool?

`SSH_ASKPASS_REQUIRE=force bw_add_sshkeys`

**Comment by zjean** [comment]
Hi @joaojacome ,
That works for me!
