### ISSUE TITLE
Error loading key "(stdin)": invalid format

### ISSUE THREAD

**Issue by lyc8503** [joaojacome/bitwarden-ssh-agent#38]
The script does not work in `Git bash(MINGW)` on Windows.

It complains `Error loading key "(stdin)": invalid format`
It seems that there's some issues related to line breaks on Windows.

But If I change code starting from line 235 as below, it works.
```
    subprocess.run(
        ["ssh-add", "-"],
        input=ssh_key.encode("utf-8"),
        # Works even if ssh-askpass is not installed
        env=envdict,
        universal_newlines=False,
        check=True,
    )
```

**Comment by charmparticle** [comment]
This brought bw-add-sshkeys from non-working to working on my linux machine

**Comment by joaojacome** [comment]
Fix for this one has been merged
