### ISSUE TITLE
Require passphrase input even though passphrase field is set on Mac

### ISSUE THREAD

**Issue by Romira915** [joaojacome/bitwarden-ssh-agent#43]
It seems that setting SSH_ASKPASS and SSH_KEY_PASSPHRASE as environment variables avoids input.
However, I think the environment variables are ignored on Mac.
Do you know of a way to avoid passphrase input on  Mac?

**Comment by joaojacome** [comment]
Hello!
@Romira915 please try this: https://github.com/joaojacome/bitwarden-ssh-agent/issues/26#issuecomment-1207253606

**Comment by Romira915** [comment]
@joaojacome 
Thank you! I tried that and it solved the problem.
