### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by flossgeek** [joaojacome/bitwarden-ssh-agent#44]
After logging the client in to my own vaultwarden server (which functions just fine), I tried running the python script. I am getting the following log back however:
```
INFO:root:Getting folder list
INFO:root:Getting folder items
INFO:root:Attempting to add keys to ssh-agent

/snapshot/clients/node_modules/node-fetch/lib/index.js:1505
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to http://localhost/attachments/<long_string>/<another_long_string> failed, reason: connect ECONNREFUSED ::1:80
    at ClientRequest.<anonymous> (/snapshot/clients/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:537:28)
    at Socket.socketErrorListener (node:_http_client:465:9)
    at Socket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}

Node.js v18.5.0
WARNING:root:Could not add key to the SSH agent
```
When I try and browse the link via a web browser with `localhost` replaced by my actual server domain, the attachment downloads successfully. Why would it point back to localhost in this scenario?

**Comment by joaojacome** [comment]
That error is coming directly from Bitwarden CLI. It might be that your current BW cli configuration is pointing to localhost instead of your actual domain?

**Comment by flossgeek** [comment]
Yep, it was an issue with global overrides in the vaultwarden config (https://community.bitwarden.com/t/cant-download-attachements-from-self-hosted-bitwarden/30136), it had nothing to do with your script which is working great now :).
